---
title: "Linear Regression Project"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
"Original seed -> 3.1415"

"Data Orginization"
#Gather Data and Set Seed
  library(robustHD)
  library(leaps)
  library(splitstackshape)
  library(caret)
  library(olsrr)
  library(dplyr)

GD<-function(){
  
  set.seed(3.1415)
  options(scipen=999)
  Data<<-data.frame(read.csv("/Users/andrew/Documents/Spring 2022 Classes/QF112 /Homeworks/QF112 Project/LifeExp.csv"),c(1:1005), stringsAsFactors = TRUE)
  n<-length(Data$LifeExpectancy)
  Data<<-Data[-397,]
  
  #Convert Catagoricals to numerics then factors
  #Data<<-data.frame(data.matrix(Data))
  Data$Country<<-factor(Data$Country)
  
  #Make Stratified Sample                  
  Train1 <- stratified(Data,"Country",.5)
  
  Test<<-subset(Data, !(Data$c.1.1005. %in% c(Train1$c.1.1005.)))
  Train2<-Test[sample(1:526,24),]
  Test<<-subset(Test, !(Test$c.1.1005. %in% c(Train2$c.1.1005.)))
  Train<<-rbind(Train2,Train1)

  #Make Separate Dependents
  TrainD<<-Train$LifeExpectancy
  TestD<<-Test$LifeExpectancy
  
  #Remove Index & dependent variable 
  Train<<-Train[,-c(3,22)]
  Test<<-Test[,-c(3,22)]
  Data<<-Data[,-c(22)]
}


"Parameter Testing"
#Check ANOVA
anva<-function(){
      ANOVA<-aov(LifeExpectancy~Country, data = Data)    
      summary(ANOVA)
}


#Second double subset selection and normal linear model(including country)
Pslct2<-function(){
      
        #Subset Selection(excluding Countries)
        
        SubSel1<<-regsubsets(TestD~.,data=Test[,-1],method = "forward")
        
        
        #Isolate Best Independent Variables(excluding Countries)
        coefs<-coef(SubSel1,5)
        name<<-c(names(coefs[-1]),"Country")
        Train<<-Train[name]
        Test<<-Test[name]
        
        #Subset Selection(Including Countries)
        model<-lm(TestD~.,data=Test)
        SubSel2<<-ols_step_best_subset(model,method = "forward")
        
        #Isolate Best Independent Variables(Including Countries)
        name<<-c(unlist(strsplit(SubSel2$predictors[3],split = " ")))
        Train<<-Train[name]
        Test<<-Test[name]
        
        #Use Parameters to Make Model and Prediction
        model2<<-lm(TrainD~.,data = Train)
        
        Pred<<-predict(model2,Test)
        MSE<<-mean((TestD-Pred)^2)

}

GO<-function(){
    GD()
    anva()
    Pslct2()
    summary(model2)
    plot(model2)
}

GO()

```

```{r}
"Functions not used in final model - Used in Developement"

#First subset selection and PCA model(not including country due to PCA)
Pslct1<-function(p){
        #Subset Selection
        SubSel<<-regsubsets(TestD~.,data=Test[,-1],method = "forward")
        
        #Isolate Best Independent Variables
        coefs<-coef(SubSel,p)
        name<<-c(names(coefs[-1]))
        Train<<-Train[name]
        Test<<-Test[name]


        #Use Parameters to Make Model and Prediction
        modelPCA <<- train(
        TrainD~ .,
        data = cbind(Train,TrainD),
        method = 'lm',
        preProcess = c("center", "scale", "pca")
        )
        Pred<<-predict(modelPCA,Test)
        MSE<<-mean((TestD-Pred)^2)
}

#Combines insignificant levels for Pslct2()
GetLev<-function(i){
  sum<-summary(model2)
  
  if(is.na(sum$coefficients[,4][i])==TRUE){
    print(Clevs)
    
    #Assigns the list of insignificant levels to the same arbitrary insignificant level.
    levels(Test$Country)[as.numeric(Clevs)]<<-c(14)
    levels(Train$Country)[as.numeric(Clevs)]<<-c(14)
    
    #Makes a new model with consolidated levels
    
    model2<<-lm(TrainD~.,data = Train)
    
    #New MSE, very slightly higher. Don't know if this really makes much of an improvement.
    Pred<<-predict(model2,Test)
    MSE<<-mean((TestD-Pred)^2)
  }
  
  else{
    #If the p-value is insignificant at alpha==.05 then that level is stored to be used in the first if statement.
    if(sum$coefficients[,4][i]>.05){
    level<-names(sum$coefficients[,4][i])
    Clevs<<-c(Clevs,substr(level,8,nchar(level)))
    GetLev(i+1)
    
    }
    
    #Recursively repeats if significant
    else{
      GetLev(i+1)
    }
  }
}

```

